theme: jekyll-theme-minimal
logo: /assets/img/logo-msp-oplati.png
show_downloads: true
github:
  zip_url: https://example.com/download.zip
  another_url: another value
title: mspOplati
#description: [A short description of your site's purpose]
